<?php include('_header.php');?>
<body>
<?php include('_navbar.php')?>
<div class="mainRestauration">
<?php include('_navVille.php'); ?>

    <section id="content">
        
        <h2>La naissance du <span>Lieu Boisé</span></h2>
        <p>Emergé de la mer flandrienne (actuelle Mer du Nord), d’assèchements de sables et de vases d’origine fluviale, le village de LOON (qui signifierait pour les uns « lieu boisé », pour d’autres « canards  ») se concrétise à la fin du 11ème siècle. A la fin du 12ème siècle, Loon a une réelle existence, mais deux fléaux majeurs menacent à chaque instant : les inondations et les guerres… Ce n’est qu’à partir de 1756 que Loon se remet de ces conflits et de périodes d’inondations  et prend alors sa physionomie définitive. Loon serait devenue française après la Paix des Pyrénées (1659). L’époque est marquée par la fuite des flamands vers la Flandre orientale et, simultanément, par une immigration d’origine calaisienne, boulonnaise et picarde. Loon commence alors à se franciser de sorte que l’on finira par ne plus parler que le français à Loon, sauf dans les brouckes où l’usage du flamand a persisté jusqu’à très récemment. En 1791, on estime la population à environ 1 000 individus. C’est l’agriculture qui rythme la vie de la totalité des Loonois au travers des travaux saisonniers. On y récolte surtout des céréales (blé, orge, avoine…). A la fin du 19ème, les cultures de la chicorée, de la  carotte et de la betterave prédominent et deviennent les principales activités agricoles. A la veille de la Révolution Française, la grogne des paysans loonois grandit à l’égard du magistrat de Bourbourg (équivalent d’un conseil municipal). Les cahiers de doléances rédigés, le décret du 14 décembre 1789 permet à Loon de devenir une commune indépendante, capable de choisir ses élus et de gérer son administration. En 1889, pour éviter toute confusion avec Laon (02), le conseil décide le changement de nom de la commune qui s’appellera ensuite «  Loon-Plage ». Quelques mois plus tard, émerge l’idée de créer une station balnéaire sur la plage de Loon-Plage. En 1894, un casino est construit ainsi qu’un hôtel et des chalets : c’est la plage du Clipon, nouveau lieu de vacances à la mode où l’on peut observer les allées et venues des gens fortunés. </p>

        <h2>Le <span>nouveau visage</span> de Loon-Plage</h2>
        <div class="flexBox">
            <img src="./public/images/avenue_marronier.jpg" alt="Ancienne Photo de Loon-Plage" class="oldImg" />
            <p>En 1929, il existe 16 sècheries à chicorée sur le territoire loonois  : l’économie est essentiellement basée sur la culture de cette racine, et complétée par l’exportation massive de carottes, betteraves, navets… A partir de 1965, tout s’accélère… A la suite de l’abandon du site balnéaire du Clipon, l’extension du port de Dunkerque et la rétrocession d’une immense partie de la plage ouvrent le chapitre de l’industrialisation loonoise. L’ambition de faire de Dunkerque un port d’intérêt national entraîne la création d’écluses et de bassins toujours plus spacieux. Les expropriations se multiplient et les industries s’implantent sur le littoral… Loon-Plage devient alors une ville à forte concentration industrielle. Corrélativement, de nombreuses exploitations agricoles disparaissent. En 1968 est créée de la Communauté Urbaine de Dunkerque (CUD). Loon-Plage devient membre de la CUD afin de répondre au problème nouveau du relogement des loonois expropriés. Le visage de Loon-Plage poursuit sa métamorphose.</p>
        </div>

        <h2>Du village à <span>la ville</span></h2>
        <p>Dès les années 1960, Loon-Plage doit se préparer à passer du village à la ville. Le décret ministériel du 16 octobre 1958 a constitué 27 communes du littoral en groupement d'urbanisme et la commune est directement concernée, menacée même, par le plan directeur soumis aux collectivités en août 1960 : pas moins de 2 600 hectares, soit les deux tiers de la superficie communale, sont initialement réservés à l'extension du port par les services de l'État, ce qui, dans un avenir proche, entraîne la disparition d'exploitations agricoles, des hameaux du Clipon et du Westhouck ainsi que de nombreuses habitations situées notamment dans le secteur du Warlande. Cette décision, qui est sans appel, concerne alors près de la moitié de la population. Loon-Plage, qui se considère sacrifié sur l'autel de l'expansion industrialo-portuaire, cherche alors à se défendre pour ne pas se retrouver étouffé par l'emprise du Port autonome et émet des réserves lors de l'enquête publique qui est lancée en 1967. Celles-ci portent sur le nouveau cimetière, récemment créé, une préférence pour une déviation de la RN 40 au nord et non pas au sud, la création de lotissements pour le relogement des personnes expropriées ainsi que la création d'une zone d'habitation pour assurer l'extension urbaine.</p>
        <div class="flexBox">
            <img src="./public/images/ecolefille.jpg" alt="Ancienne Photo de Loon-Plage" class="oldImg" />
            <p>La commune ne peut rester isolée dans ce combat et doit se faire entendre. Le temps de la réflexion aidant, elle adhère, le 14 novembre 1969 à la Communauté de Dunkerque, officiellement créée en octobre 1968 et mise en place le 1er janvier 1969 sous la présidence d'Albert Denvers. Elle va dès lors bénéficier de l'appui logistique de l'institution intercommunale dont les compétences portent en particulier sur l'urbanisme, les équipements et les chemins vicinaux.
            Les familles expropriées, indemnisées, migrent vers deux quartiers du bourg, celui de la Gare et celui des Kempes qui n'est pas encore structuré, présentant de nombreux signes d'insalubrité. Ces bouleversements, qui créent des traumatismes, conduisent les municipalités successives à mettre en place un véritable plan de modernisation et de construction. Ainsi, d'importants travaux de voirie et d'assainissement sont réalisés aux Kempes, désormais relié au bourg par le Gai Logis. La réhabilitation de ce quartier jusque-là considéré comme les bas-fonds de Loon-Plage, va redorer son blason.
            Force est de constater que le Port autonome représente le principal facteur économique et industriel ayant influencé l'urbanisme loonois et, dès les années 1970, la politique de la ville a consisté à initier l'accompagnement de cette mutation. Les grandes lignes de cette démarche s'appuient sur le développement de structures d'accueil nécessaires en termes de logements et d'équipements collectifs ; des conditions d'accueil et d'accès pour l'implantation des activités industrielles ; la réalisation d'une ceinture boisée au Nord de la zone urbaine afin de préparer la confrontation entre habitat et industrie ; et la restructuration de l'habitat existant. Dès 1971, la Communauté urbaine demande la création d'une ZAD (Zone d'aménagement différé) au sud de la RN 40, pour assurer le relogement des familles expropriées ainsi que la création des équipements scolaires, sportifs et socio-éducatifs. Les premiers permis de construire sont signés avant l'échéance municipale de 1977.</p>
        </div>

        <h2>2001, l'année <span>décisive</span></h2>
        <div class="flexBox">
            <img src="./public/images/lpcolor.jpg" alt="Ancienne Photo de Loon-Plage" class="oldImg" />
            <p>Le résultat obtenu par la liste de Jean-Claude Delalonde aux élections municipales de 1995 n'exprimait pas une franche adhésion de la population à la politique menée depuis une décennie et semblait déjà traduire aussi une certaine usure prématurée du pouvoir. Certes, les Loonois reconnaissent les qualités de leur maire sur le plan de la gestion communale, le considérant comme un excellent technicien, opiniâtre et pugnace, mais ils lui reprochent de n'être qu'un homme de dossier, distant avec ses concitoyens et quelque peu éloigné de la vie publique.
            Aux élections municipales de mars 2001, Jean-Claude Delalonde doit affronter un nouvel adversaire : Éric Rommel, Loonois de souche depuis huit générations du côté maternel, directeur de cabinet de Léon Panier, maire de Gravelines. Son engagement en politique date de 1989, date à laquelle il s'était présenté, comme il le fit en 1995, sur la liste de Régis Fauchoit. L'équipe qu'il a constituée est « multi-étiquettes », allant de membres de l'UMP, du PS, du PC, de Chasse Pêche Nature et Traditions, aux écologistes. Cette liste plurielle, constituée pour ratisser large, recueille, dès le premier tour de scrutin, l'adhésion d'une majorité de l'électorat avec 52,46 % des suffrages exprimés qui lui donnent 22 sièges sur 29. La volonté populaire de rompre avec une certaine forme de technocratie s'est nettement exprimée et le changement est radical.
            7Force est de constater que la nouvelle politique municipale, qui s'appuie sur une approche de proximité, de disponibilité, d'accessibilité et d'exercice de la démocratie locale, est particulièrement appréciée au fil des ans, comme le démontrent les résultats des scrutins municipaux ultérieurs. En mars 2008, l'équipe sortante est reconduite dès le premier tour de scrutin avec 70,07 % des suffrages exprimés soit 850 voix de plus qu'en 2001. La liste d'opposition conduite par Jean-Claude Delalonde n'obtient que quatre sièges et celui-ci décide de démissionner. La liste d'Éric Rommel est plébiscitée en mars 2014 par l'électorat loonois avec 81,36 % des suffrages exprimés. Ce témoignage de confiance tient à la méthode d'administration mais surtout aux réalisations particulièrement nombreuses de la décennie écoulée. Réhabilitation, transformation et extension des équipements existants, nouvelles constructions, couronnent une politique de grands chantiers : un nouvel Espace Jeunes doté d'un Centre d'animation jeunesse et ouvert aux associations, une Maison des associations, une maison des Anciens, les extensions de l'École de musique avec la construction de six salles de classe, et de la Halte garderie, la construction d'un Centre de restauration scolaire, la rénovation de la salle de sports Marcel-Rommel, la mise aux normes des vestiaires du stade Giovanni-Martello, l'aménagement du Parc Galamé, etc. À noter que l'ancienne école de garçons abrite le Centre communal d'action sociale (CCAS) et que l'ancienne école des filles est devenue l'Espace Michel-Simon pour la restauration et les après-midi récréatives des aînés.
            Durant la période 1999-2007, la municipalité doit faire face à une baisse de la population qui passe de 6506 à 6208 habitants, et ceci malgré le fait que 100 logements ont été construits entre 2001 et 2007. Ce phénomène est dû à la baisse des habitants par ménage et à l'augmentation du nombre de personnes seules et de familles monoparentales. Face à ce constat, existe une volonté municipale, exprimée en 2008, de poursuivre l'urbanisation en envisageant la construction de 450 logements sur 10 ans.</p>
        </div>
    </section>

</div>

<?php include('_footer.php'); ?>